# Generated by Django 5.1.2 on 2025-05-03 01:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Provider Name')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='Commission Rate (%)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_start', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Starting Cash')),
                ('float_start', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Starting Float')),
                ('cash_end', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ending Cash')),
                ('float_end', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ending Float')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_balanced', models.BooleanField(default=False, verbose_name='Is Balanced')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='multisyncbalance.provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
            },
        ),
    ]
